### ISSUE TITLE
plugin dev doc: describe when to create methods vs visualizers

### ISSUE THREAD

**Issue by jairideout** [qiime2/docs#112]
This question often comes up -- when should the output be an artifact vs a visualization? Having some guidelines in place would be helpful.

**Comment by jakereps** [comment]
Was this resolved? This blurb seems somewhat targeted towards this issue

https://github.com/qiime2/docs/blob/master/source/plugins/developing.rst#define-functionality

> QIIME 2 users will access your functionality as QIIME 2 ``Actions``. These ``Actions`` can be either ``Methods`` or ``Visualizers``. A ``Method`` is an operation that takes some combination of ``Artifacts`` and ``Parameters`` as input, and produces one or more ``Artifacts`` as output. These output ``Artifacts`` could subsequently be used as input to other QIIME 2 ``Methods`` or ``Visualizers``. A ``Visualizer`` is an operation that takes some combination of ``Artifacts`` and ``Parameters`` as input, and produces exactly one ``Visualization`` as output. Output ``Visualizations``, by definition, cannot be used as input to other QIIME 2 ``Methods`` or ``Visualizers``. ``Methods`` therefore can produce intermediate or terminal output in a QIIME analysis, while ``Visualizers`` can only create terminal output.
