### ISSUE TITLE
q2 filtering tutorial- add examples of OR and IN SQL uses.

### ISSUE THREAD

**Issue by shiffer1** [qiime2/docs#115]
In the q2 filtering tutorial, add in examples for filtering the feature table with two instances of a category using AND and OR SQL commands like those found in the docs.

**Comment by jairideout** [comment]
Thanks @shiffer1! Note that we need to add examples to the filtering tutorial, which is in this docs repo. AFAIK there aren't existing examples (except on Slack) for filtering with AND and OR.

**Comment by jairideout** [comment]
Spoke offline with @shiffer1. The filtering tutorial would benefit from examples of `OR` and `IN` keywords -- there is already an `AND` example.

**Comment by shiffer1** [comment]
Note that we should also provide a NOT example as well.

**Comment by jairideout** [comment]
See also this [forum post](https://forum.qiime2.org/t/passing-in-filtered-table-qza-file-for-alpha-and-beta-diversity-analysis/458/5) for more SQL examples to add to the tutorial.
