### ISSUE TITLE
update FastTree conda install channel to bioconda

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/docs#119]

**Comment by jairideout** [comment]
This is important for the next release -- @wasade ran into it and also our institutional cluster.

**Comment by jairideout** [comment]
Reopening until busywork is finished testing.

**Comment by jairideout** [comment]
`fasttree` is now obtained from `bioconda` and has been tested with busywork and Travis-CI.

**Comment by ebolyen** [comment]
:tada:
