### ISSUE TITLE
display plugin short/long descriptions in plugin directory Sphinx extension

### ISSUE THREAD

**Issue by jairideout** [qiime2/docs#120]
The QIIME 2 framework and q2cli now support plugin short/long descriptions (thanks @maxvonhippel for hooking that up!). It would be great to include these descriptions in the [plugin directory Sphinx extension](https://github.com/qiime2/docs/tree/master/source/sphinx_extensions/plugin_directory) that auto-generates plugin docs.

There's an example of the rendered plugin directory docs [here](https://docs.qiime2.org/2017.2/plugins/available/). We'd want the "long" description at the top of the page, in the same group as version, citation text, etc. (e.g. check out [this page](https://docs.qiime2.org/2017.2/plugins/available/diversity/)). We'd want the short description to appear in the title heading of that page (e.g. "diversity: short_description", or just "diversity" if there isn't a short description).

@maxvonhippel, let me know if you need clarification on where to display these descriptions (I can post screenshots if it helps).

**Comment by maxvonhippel** [comment]
Sounds great!  I'll look through this sometime tomorrow evening or next week and let you know if I have any questions!
