### ISSUE TITLE
QIIME to QIIME2 translator

### ISSUE THREAD

**Issue by shiffer1** [qiime2/docs#124]
**Improvement Description**
Someone had a great idea in Dr. Caporaso's class about having a page that has QIIME 1 commands mapped to QIIME 2 commands. Something like to extract barcodes in QIIME 1 you used `extract_barcodes.py` and in QIIME 2 you use `qiime extract_barcodes` (I know this isn't the real command , but an example).

**Comments**
This could serve as a useful tool for folks familiar with QIIME to transition into QIIME 2

**Comment by gregcaporaso** [comment]
@antgonza and I started this in a Google Spreadsheet [here](https://docs.google.com/spreadsheets/d/1AOyA84lGPBk5C2Uflg_pILEL75a6_gdY6SK3ltOt44E/edit?usp=sharing). This will also be useful for tracking what we still need to port. We can take this content and move it to a nicer document at some point if that seems useful.

**Comment by jairideout** [comment]
[forum x-ref](https://forum.qiime2.org/t/suggestion-beginner-flow-chart-tutorial/2292?u=jairideout)

**Comment by cherman2** [comment]
Closing since most users are not familiar with qiime anymore.
