### ISSUE TITLE
ANCOM Clarification

### ISSUE THREAD

**Issue by thermokarst** [qiime2/docs#125]
The `Moving Pictures` [tutorial](https://docs.qiime2.org/2017.2/tutorials/moving-pictures/#differential-abundance-analysis) says the following about `ancom`:

> ANCOM operates on a `FeatureTable[Composition]` QIIME 2 artifact, which is based on relative frequencies of features on a per-sample basis, but cannot tolerate frequencies of zero. We work around this by adding a pseudocount of 1 to every count in our `FeatureTable[Frequency]` table. 

The prose indicates that we are working with relative frequencies, but the registered input type to the `add-psuedocount` method is `FeatureTable[Frequency]`. Looking at the [plugin](https://github.com/qiime2/q2-composition/blob/master/q2_composition/_impute.py), it doesn't look like we are converting from `Frequency` to `RelativeFrequency` anywhere. Am I misunderstanding something? Do we need to update this prose to clarify something?

**Comment by jairideout** [comment]
Yeah this text could be updated to be more explicit about the data flow (we could adapt your [forum post text](https://forum.qiime2.org/t/using-ancom-to-identify-diferentially-abundant-features/463/4)).
