### ISSUE TITLE
`conda install --file` wipes existing environment content

### ISSUE THREAD

**Issue by jakereps** [qiime2/docs#131]
**Improvement Description**
Using `conda install --file` within an existing environment in order to install `qiime2` core using the link online will wipe out all existing installs and make your environment only match the file. This should be noted, or possibly find a way for it to not nuke your environment when installing.

**Comment by jakereps** [comment]
Kind of confused on if this is still an issue or not. Ran the command recently and things seemed to stay in place. If someone could reproduce it might hold more weight, or it could have been some older version of conda or something causing it.

**Comment by jairideout** [comment]
Looks like this may still be an issue: https://forum.qiime2.org/t/problem-upgrading-to-2017-6/719
