### ISSUE TITLE
Clarify Emperor descriptions in tutorials

### ISSUE THREAD

**Issue by thermokarst** [qiime2/docs#149]
- The Moving Pictures Tutorial has [some text](https://github.com/qiime2/docs/blame/master/source/tutorials/moving-pictures.rst#L306) about the axis labels --- this should be updated to reflect the recent [upgrade to emperor](https://github.com/qiime2/q2-emperor/pull/39#issuecomment-302795942)

- The FMT Tutorial [refers to a non-existent](https://github.com/qiime2/docs/blame/master/source/tutorials/fmt.rst#L151) `Note` --- perhaps we could just link back to the MP paragraph/section describing Emperor (or, make that section in MP a more generic `Note`, and have both tutorials reference that).

**Comment by maxvonhippel** [comment]
Just addressed this in my [PR](https://github.com/qiime2/docs/pull/150).  Let me know what you think :)
