### ISSUE TITLE
q2studio install instruction aren't clear about when to activate env

### ISSUE THREAD

**Issue by thermokarst** [qiime2/docs#154]
This came up [previously](https://github.com/qiime2/docs/issues/102), but still seems to be a [bit confusing](https://forum.qiime2.org/t/error-installing-q2studio/657). Perhaps we need to add an explicit `source activate qiime2-$RELEASE` at the top of the page? We could retool the [`note`](https://github.com/qiime2/docs/blame/master/source/interfaces/q2studio.rst#L33), or drop it altogether, I have no preference.

**Comment by maxvonhippel** [comment]
This can be assigned to me.
