### ISSUE TITLE
UX BUG: Native install (mac vs linux)

### ISSUE THREAD

**Issue by thermokarst** [qiime2/docs#169]
This has come up several times recently: users are accidentally copying and pasting the mac os install commands when installing on a linux host, likely because the mac os commands occur first. Maybe we should replace this section with a tabbed panel (like the `download` blocks). The three tabs would be a default "instructions" page, instructing users to click either the mac tab or the linux tab, and then the other two tabs would be the aforementioned mac and linux tabs. This might help prevent the copy-paste issues, although maybe it poses some new problem that I am not considering. Thoughts?

**Comment by jairideout** [comment]
:+1: I like that idea! Many other software install instructions take a similar approach and it seems to work well.

**Comment by maxvonhippel** [comment]
This can be assigned to me.
