### ISSUE TITLE
make Moving Pics "sample metadata" link easier to find

### ISSUE THREAD

**Issue by jairideout** [qiime2/docs#188]
In the Moving Pictures tutorial there's a link to a sample metadata Google Sheet for users to inspect and validate with Keemei. It's pretty difficult to find the link. Perhaps adding the link to the "tip" box will help users find it when trying out Keemei.

Hard to find spreadsheet link:

![image](https://user-images.githubusercontent.com/1847232/29327271-9ab4d784-81bc-11e7-8b26-ffcade38a9cd.png)

Adding the spreadsheet link to this "tip" box could help:

![image](https://user-images.githubusercontent.com/1847232/29327323-bbc6aede-81bc-11e7-80b3-2b457465b63c.png)

**Comment by colinbrislawn** [comment]
Let's improve the full tutorial! #304
