### ISSUE TITLE
update FMT tutorial with paired-difference testing

### ISSUE THREAD

**Issue by jairideout** [qiime2/docs#213]
The FMT tutorial is outdated now that q2-longitudinal exists:

![image](https://user-images.githubusercontent.com/1847232/31411453-8f75cbc2-adc6-11e7-829a-f87d7fdc0f8f.png)

We should remove this note and update the text to reference the q2-longitudinal tutorial and add some paired-difference questions to the FMT tutorial.

@nbokulich would you be available to work on this for 2017.10?

**Comment by nbokulich** [comment]
Will do!
