### ISSUE TITLE
port OTU picking community tutorial into docs

### ISSUE THREAD

**Issue by jairideout** [qiime2/docs#219]
Tutorial is here:

https://forum.qiime2.org/t/clustering-sequences-into-otus-using-q2-vsearch/1348?u=jairideout

**Comment by nbokulich** [comment]
also link to this tutorial from the moving pics tutorial (even though we recommend denoising methods, non-Illumina users may benefit, as brought up [in the forum](https://forum.qiime2.org/t/problem-with-dad2-return-code-1/2500/13?u=nicholas_bokulich))
