### ISSUE TITLE
DOC: release-specific URL is confusing for users

### ISSUE THREAD

**Issue by colinbrislawn** [qiime2/docs#290]
**Bug Description**
Each release of Qiime 2 includes new documentation, under a new URL. This change in URL confuses Google indexing and dramatically reduces discoverability of new documentation. 

**Screenshots**
![screen-shot-2018-03-06-at-12 36 01-pm](https://user-images.githubusercontent.com/10355152/37057236-939d6e74-213b-11e8-8fcd-62e5a58a1aab.png)

This 4th place ranking is a month after launch. In the days after release, when users were looking for the new plugins and how to use them, the new page was nowhere to be found.

---

Making matters worse, that top link to the old documentation doesn't point to the specific tutorial or function:

![screen-shot-2018-03-06-at-12 43 21-pm](https://user-images.githubusercontent.com/10355152/37057719-2817bcca-213d-11e8-8526-aaf8bbd3dda1.png)

---

The changing URLs also break [recommendations on the forums](https://forum.qiime2.org/t/plugin-error-feature-classifier-extract-reads/2493/14).

**Comments**
@nbokulich
> we do have a [data resources page](https://docs.qiime2.org/2017.12/data-resources/)

**References**
Not anymore! 
I mean, we still do but it's here: <https://docs.qiime2.org/2018.2/data-resources/>
And in a few weeks it'll be here: <https://docs.qiime2.org/2018.3/data-resources/>

**Comment by thermokarst** [comment]
Thanks @colinbrislawn - we have actually already implemented a [`robots.txt`](https://github.com/qiime2/docs.qiime2.org/blob/gh-pages/robots.txt) file to direct Google's webcrawlers to ignore those old docs, but Google is going to do whatever Google wants to do on their end. Similarly, we have requested (several times) the Google remove existing indexes for those docsets (via their web console), and have had no luck there, either. @ebolyen and I worked up a really simple system as part of our [`dev-docs`](https://github.com/qiime2/dev-docs) initiative that will handle all of the issues you brought up here. Once we are comfortable with the behavior in the dev-docs, we will backport here to the user docs. Stay tuned!

PS - 

You can click on "show me the content on this page" in order to view the old results, at the URL you visited. I just want to clarify, we don't delete or remove old versions of the docs, we just warn people with this alert that they are looking at old docs.

**Comment by colinbrislawn** [comment]
I knew the team would be working to solve this! I'm sorry the google tools are not working as expected... 

I also like how all versions of the docs are preserved, and that the URLs clearly differentiate versions. Using `https://docs.qiime2.org/latest` would be easy, but this version is very clear. I hope the changes in dev-docs make this super easy for new users!

**Comment by colinbrislawn** [comment]
Good morning,

These links also cause confusion for users. https://forum.qiime2.org/t/merging-reads-from-2-lanes-of-the-same-sample/8169 

> I see that this function is no longer current

That function _is_ current and included in the newest release of qiime, but this user couldn't find it. Our current method for showing depreciated documentation prevents users from finding the docs they need.

**Comment by ebolyen** [comment]
Agreed. We'd really like to move the user docs to something like the dev docs, which has a "latest" version and is able to redirect backwards to a canonical version if the page doesn't exist, but it's been stuck in our todo list for a while.

Also, we'd like to use the library for almost everything plugin related (including tutorials), so we've been kind of limping along with the user docs as is for a while :(

**Comment by colinbrislawn** [comment]
Can we revisit this issue? I think it's gotten worse... 😬 

This [user](https://forum.qiime2.org/t/trouble-installing-qiime2-after-multiple-tries-too-long-loading/25504) installed Qiime2 from a YouTube video, which makes sense because

<details>
<summary>Google results for "install qiime2" </summary>

![image](https://user-images.githubusercontent.com/10355152/219224272-d28024f4-c52a-4bd5-9242-58ac47ecefe4.png)

</details>

https://docs.qiime2.org/2022.11/install/native/ never appears on this page

**Comment by colinbrislawn** [comment]
I've finally looked into this.

I agree that https://docs.qiime2.org/latest/ is still the best way forward. When folks come to old pages, we may want to use buttons like this and the UX should be as smooth as possible.

As far as I can tell, `/versions.js` makes the full-screen warning and is not in this repo. You can view it here: https://docs.qiime2.org/versions.js

Perhaps it could look like this, with dynamic links and text built from the JSON
<img width="1249" alt="Screenshot 2023-08-24 at 8 21 39 PM" src="https://github.com/qiime2/docs/assets/10355152/77a24234-4ae4-43c7-a8f6-058879a67bdf">


<details><summary>Details</summary>

```
<div class="btn-group">
    <button class="btn btn-primary">View the newest version of this page for Qiime2-yyyy.mm</button>
    <button class="btn btn-secondary">View the old version of this page for Qiime2-yyyy.mm</button>
</div>

```

</details>

**Comment by lizgehret** [comment]
@ebolyen I think this would be straightforward to do, we'd just create the 20XX.Y release docs titled `latest` and then modify the 20XX.Y-1 release to be it's epoch (vs. latest) with each new release. Any reason we'd want to hold off on implementing this in the 2023.9 epoch?

**Comment by gregcaporaso** [comment]
This is being closed b/c we're going to solve this using ReadTheDocs, following the impending user docs refactor (see https://develop.qiime2.org/en/latest/docs/user-documentation.html#plans-for-refactoring-of-user-documentation).
