### ISSUE TITLE
classic/tsv biom table to qza

### ISSUE THREAD

**Issue by antgonza** [qiime2/docs#297]
**Improvement Description**
During a presentation a potential user asked me, how easy was to import their data into Qiime2 to take advantage of the analyses and visualizations. Thus, I believe it will be worth adding some documentation on this with a small example.

**Comments**
If we agree on having this, I could work on it.

**Comment by colinbrislawn** [comment]
Yes! The [biom-format examples](http://biom-format.org/documentation/biom_conversion.html) were so helpful for newcomers and I would love to see that for Qiime 2.

**Comment by colinvwood** [comment]
covered by #309
