### ISSUE TITLE
RawSequences is not described in semantic types

### ISSUE THREAD

**Issue by git-ingham** [qiime2/docs#31]
In the description of semantic types (https://docs.qiime2.org/2.0.6/semantic-types/), RawSequences is missing.  And, if there is any documentation on it (e.g., required format for creating an artifact from sequence data), Google does not know about it.  All I was able to find was the tutorial that made use of it, but never really described it.  I can read the source code and figure it out, but it would be much more efficient if it was well-documented somewhere.

I am a CS person moving into bioinformatics, if this background helps explain my thought processes.

**Comment by ebolyen** [comment]
Thanks @git-ingham! This system is still alpha so we have a *lot* of docs yet to write!

**Comment by jairideout** [comment]
Latest master has `RawSequences` included on the [semantic types page](https://docs.qiime2.org/2.0.6/semantic-types/) page. It links to the `q2-demux` plugin where the type is defined, and also to the [importing sequence data tutorial](https://docs.qiime2.org/2.0.6/tutorials/import-sequence-data/), which describes the required sequence data format in more detail. Note: these changes are not yet on the live site, they'll be available when version 2017.2.0 is released.

Thanks for reporting this issue @git-ingham!
