### ISSUE TITLE
broken link in installation instructions

### ISSUE THREAD

**Issue by rrohwer** [qiime2/docs#388]
Under directions for Natively installing qiime2: https://docs.qiime2.org/2018.11/install/native/#

The wget link in the mac OS 64-bit tab is broken:

```
$ wget https://data.qiime2.org/distro/core/qiime2-2018.11-py35-osx-conda.yml
--2019-03-04 12:00:17--  https://data.qiime2.org/distro/core/qiime2-2018.11-py35-osx-conda.yml
Disabling SSL due to encountered errors.
```

**Comment by thermokarst** [comment]
Hi @rrohwer that error is typically caused by having an outdated `wget` tool (did you remember to run that install step?) What version of `wget` do you have? I just checked with 1.20.1 and the environment file downloaded as expected! In the meantime, you can try downloading with a different tool (for example, Firefox or Chrome), if you are unable to install a new version of `wget`. Also, in the future, we provide user support for the QIIME 2 project at https://forum.qiime2.org. Thanks!

**Comment by thermokarst** [comment]
Hmm, I just looked into this a bit more, looks like `conda`'s `wget` is having issues with the SSL cert, too, so installing wget in conda might not help. This has to do with the root certificate [authority changing on us](https://sectigo.com/sectigo-story-faq), some tools and environments are unfamiliar with the root authority in the cert chain.

**Comment by thermokarst** [comment]
Conda's wget is pretty broken:

```bash
 wget https://google.com
--2019-03-04 12:26:02--  https://google.com/
Disabling SSL due to encountered errors.
```

Yikes!

**Comment by rrohwer** [comment]
Thanks! The work-around I found for now was to just find it directly on github. I went to https://github.com/qiime2/environment-files, found the most recent version with a release available, and copy-pasted the text to create a file of the same name in my working directory. Then I could feed that directly into the command in the tutorial: `$ conda env create -n qiime2-2019.1 --file qiime2-2019.1-py36-osx-conda.yml` This seems to have worked!

**Comment by thermokarst** [comment]
Wow! That certainly works --- just curious though, did opening https://data.qiime2.org/distro/core/qiime2-2018.11-py35-osx-conda.yml directly in your browser not work? That should prompt you with a download dialog.

**Comment by rrohwer** [comment]
Yes, the link did work pasted into my browser, but at the time I thought maybe the problem had been because it was outdated so that's why I dug around for the github page. Turns out that's not why wget was broken, but there *was* a newer release available :)
