### ISSUE TITLE
"Modernize" metadata headers in tutorial metadata files

### ISSUE THREAD

**Issue by thermokarst** [qiime2/docs#396]
**Improvement Description**
"Modernize" metadata headers in tutorial metadata files.

**Current Behavior**
Most or all of the current tutorials use the old QIIME 1 "`#SampleID`" header label.

**Proposed Behavior**
Update the sample ID header label to a new, non-Q1 label.

**Questions**
1. Which ID label? I was thinking `sample-id`...
2. Should we also standardize the other column labels?

**Comment by nbokulich** [comment]
Yes!
1. I vote `sample-id`

**Comment by thermokarst** [comment]
I started on this, which is why BW is broken:

https://busywork.qiime2.org/teams/main/pipelines/master-distribution/jobs/integration/builds/2

Need to cut a docs PR to update the column name refs in the tutorials. Planning on doing that Wednesday.
