### ISSUE TITLE
New 16s Tutorial for Workshop

### ISSUE THREAD

**Issue by jwdebelius** [qiime2/docs#402]
**Improvement Description**
@nbokulich and @thermokarst and I were discussing an alternative to the moving pictures tutorial for an upcoming QIIME 2 workshop in June. The goal would be have something slightly different and a little bit more modern

**Proposed Behavior**
I've got a fairly good start on a tutorial with 48 mouse samples from a 2016 paper and would be interested in contributing it here as a tutorial. It's quite similar to the moving pictures tutorial in terms of text/content. The current version covers:

1. Hypothesis based on a real experiment with cross sectional and longitudinal aspects
2. Metadata
2. Data loading via a manifest
3. Clustering with Deblur (~5 min)
4. Tree building via fragment insertion (11 minutes... longest run time)
5. Taxonomic classification 
6. Core diversity
    * Alpha group significance
    * Beta group significance
    * Adonis on a multivariate intersection
7. Taxonomy barchart
8. Adonis
9. Longitudinal analysis

**Comment by nbokulich** [comment]
Sounds good!

See also the `summarize-*` methods in `q2-demux`. One thing we have discussed doing more in core tutorials (i.e. those we use for workshops) is to post multiple different subsamples of the data (e.g., see [here](https://github.com/qiime2/docs/blob/0f23a659fc0b828c73fc97f6529c6987f08ae22b/source/tutorials/fmt-cdiff.rst)), so that we can do things like demux, denoise, and build phylogenies (slow steps) with small datasets in workshops, but have the full dataset available (and pre-processed) for the downstream analysis.

Your dataset does not sound too big — but it may be worth seeing if a 10% sequence subset contains sufficient data for analysis.

**Comment by jwdebelius** [comment]
I've got summarise.

Since there's interest, I'll put in a PR shortly (I just need to test building the docs, always the scariest for me!) But, the "cooking show" approach is probably a good option for faster run times. So, maybe subsample on the full table for running the data, and then have the "full" dataset somewhere else?

I did already subsample the data down to 3-5K sequences in an attempt to limit run time on the table, which produces a final depth of something like 3K seqs/sample max and comes out with a nice rarefaction depth of 1K.

**Comment by nbokulich** [comment]
sorry, I didn't mean summarize (😪) I meant `subsample-*` ! Edited above. Thanks for understanding me nonetheless.

> I did already subsample the data down to 3-5K sequences in an attempt to limit run time on the table, which produces a final depth of something like 3K seqs/sample max and comes out with a nice rarefaction depth of 1K.

Sounds perfect! 11 min of run time is not too bad either (beats what it takes to run fragment insertion on a full dataset...) and in the workshop(s) we can just be diligent about running the command at the start of that module, then talking while it runs (right now we generally go through the theory, then run the commands at the end).

**Comment by SetaPark** [comment]
Hello
Where will this workshop be held? Is it online? Thanks.

**Comment by thermokarst** [comment]
Hi @SetaPark - please check out https://workshops.qiime2.org. If you have any questions, please come find us on the QIIME 2 forum: https://forum.qiime2.org. Thanks!

**Comment by jwdebelius** [comment]
Closed via #403
