### ISSUE TITLE
should commands use explicit .qza/.qzv extension for output files?

### ISSUE THREAD

**Issue by jairideout** [qiime2/docs#41]
@thermokarst and I were chatting about this today. Commands in the docs are a little magical because output artifacts/visualizations aren't named with a `.qza`/`.qzv` extension. When only specifying the basename of the output file (sans extension), it isn't clear how the .qza/.qzv extension factors into output files. It also is hard to determine if the output filename is an artifact or visualization b/c the extension isn't in the output name. Using the basename only also makes it ambiguous whether the output is being saved as a directory or a file without an extension.

I had to explain this behavior several times during the Phoenix workshop, and it seemed to confuse users because .qza/.qzv files were a new concept that was just introduced, and the commands don't explicitly reflect how those extensions relate to output files.

Can we use explicit file extensions in the docs, and note somewhere that if the extension is omitted, it will automatically be appended?

**Comment by ebolyen** [comment]
I strongly agree with this. Even I have to do a double take whenever I look at a command because they look like directories to me.

**Comment by gregcaporaso** [comment]
I'm ok with that too.
