### ISSUE TITLE
Plugin Directory Extension is Suddenly Slow

### ISSUE THREAD

**Issue by thermokarst** [qiime2/docs#429]
**Bug Description**

Generating action help text is suddenly slower. This [old build on busywork (2019.07.28)](https://busywork.qiime2.org/teams/main/pipelines/master-distribution/jobs/integration/builds/53#L5d0915d7:813:943) ran in ~38s. A [newer build on busywork (2019.08.08)](https://busywork.qiime2.org/teams/main/pipelines/master-distribution/jobs/integration/builds/72#L5d44248f:773:903) ran in ~8m. The main thing that has changed is the addition of the deprecation API in the framework. I am filing this issue here on the docs repo since this is the main pain-point for this slow-down at present.

**Steps to reproduce the behavior**
1. run `make dummy` on the docs using 2019.7 or 2019.10.dev0

**Expected behavior**
[Generating the help text](https://github.com/qiime2/docs/blob/master/source/sphinx_extensions/plugin_directory/extension.py) should be fast (~60s).

**Comments**
1. We need to confirm that the slow-down is actually caused by the deprecation API before deciding how to proceed.

**Comment by thermokarst** [comment]
# Benchmark environments

## "Good" env (not slow)
```bash
# change to the macos yml for darwin testing
wget https://data.qiime2.org/distro/core/qiime2-2019.4-py36-linux-conda.yml -O 2019.4.yml
conda env create -n slow-2019.4 --file 2019.4.yml
conda activate slow-2019.4
```

## "Bad" env (slow)
```bash
# change to the macos yml for darwin testing
wget https://raw.githubusercontent.com/qiime2/environment-files/f606efa321d443c93aa686c173a294562f557683/latest/staging/qiime2-latest-py36-linux-conda.yml -O 2019.10.yml
conda env create -n slow-2019.10 --file 2019.10.yml
conda activate slow-2019.10
```

# Benchmarks
## `make dummy` doc

```bash
cd docs
pip install -r requirements.txt
/usr/bin/time make dummy
```

## Artifact API

```bash
/usr/bin/time python -c "from qiime2.plugins.cutadapt.methods import demux_paired; print(demux_paired.__call__.__doc__);
```

## q2cli

```bash
qiime dev refresh-cache
/usr/bin/time qiime cutadapt demux-paired --help
```

# Results
| Release     | make dummy | Artifact API | q2cli |
|-------------|------------|--------------|-------|
| 2019.4      | 39.8s      | 3.6s         | 0.2s  |
| 2019.10.dev | 429.3s     | 3.0s         | 3.1s  |

# Preliminary Conclusion

Looks like q2cli is taking ~10x longer in 2019.10.dev vs 2019.4.

@David-Rod - can you replicate these results on a Mac? Thanks!

**Comment by David-Rod** [comment]
Hey there @thermokarst,

Here are the results for my replication of the issue:

**2019.4** 
`make dummy`: 1 min 9 sec
Artifact API: 5.46 sec
q2cli: 0.36 sec
_______________

**2019.10**
`make dummy`: 11 min 22 sec
Artifact API: 5.25 sec
q2cli: 4.70 sec

**Comment by ebolyen** [comment]
Fixed in https://github.com/qiime2/q2cli/pull/228
