### ISSUE TITLE
Broken Link to CASAVA 1.8 description in importing tutorial

### ISSUE THREAD

**Issue by nbokulich** [qiime2/docs#447]
**Bug Description**
The link to the CASAVA 1.8 format description in the importing tutorial is broken. This is the broken link: http://illumina.bioinfo.ucr.edu/ht/documentation/data-analysis-docs/CASAVA-FASTQ.pdf/view

**Steps to reproduce the behavior**
Go to http://illumina.bioinfo.ucr.edu/ht/documentation/data-analysis-docs/CASAVA-FASTQ.pdf/view

**Expected behavior**
Links should go places

**Questions**
Where should this go? Do we have a replacement?

**Comment by cherman2** [comment]
Closing because Colin made a duplicate of this issue and there has been some discussion on there. #558
