### ISSUE TITLE
resources.qiime2.org

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/docs#48]
Create page(s) for resources similar to QIIME 1's [resources.qiime.org](http://resources.qiime.org). This will include:

- protocols (#3)
- virtual machine image download links/AMIs/etc
- reference databases
- useful datasets (link to mockrobiota, link to Qiita, ...)

**Comment by jairideout** [comment]
@gregcaporaso and I figured out a way to break these ideas up into relevant sections on docs.qiime2.org:

- protocols and educational material go in a "supplementary resources" page
- VMs get their own install page
- reference databases, trained classifiers, useful datasets go in a "data resources" page
