### ISSUE TITLE
Newer versions of pip are problematic when installing q2studio

### ISSUE THREAD

**Issue by thermokarst** [qiime2/docs#497]
**Bug Description**
The QIIME 2 Studio interface docs (Ref 1 below) show users how to install dependencies using pip. It looks like this is now failing on many user's machines (Refs 2 and 3), presumably because of newer versions of pip. It would be great to replace this with @andrewsanchez's instructions (Ref 3) that leverage conda:

```bash
conda install gevent nodejs
```

**References**
1. https://github.com/qiime2/docs/blob/master/source/interfaces/q2studio.rst
2. https://forum.qiime2.org/t/error-when-installing-qstudio-2020-11-0/18226
3. https://forum.qiime2.org/t/unable-to-run-q2studio/17920

**Comment by andrewsanchez** [comment]
The linked PR should address this.  Can you think of any other tweaks that should be made to address these issues?  Should we also remove gevent from [q2studio's setup.py](https://github.com/qiime2/q2studio/blob/df44fc924f62b34866c340fd448a08546f79926f/setup.py#L21)?

**Comment by thermokarst** [comment]
> Can you think of any other tweaks that should be made to address these issues?

Nothing comes to my mind - thanks for checking.

> Should we also remove gevent from q2studio's setup.py?

Good question - I don't think so - conda installs gevent in a manner that allows pip to "see" it, so when running `pip install .` _after_ the new `conda install ...` command you introduced in #498, pip skips installing gevent because it is all there.
