### ISSUE TITLE
PD Mice Typo: 

### ISSUE THREAD

**Issue by jwdebelius** [qiime2/docs#499]
**Bug Description**

In the PD mice tutorial a forum user reported weighted unifrac going in and unweighted unifrac emerging based on the file name:

https://forum.qiime2.org/t/permdisp-in-tutorial/18414

<img width="820" alt="Screen Shot 2021-02-08 at 9 32 25 AM" src="https://user-images.githubusercontent.com/5534846/107249508-ac606c80-69f0-11eb-8c0b-903fa30e10f9.png">

I think when I initially wrote the tutorial, the idea was to work through the last couple steps (permdisp and adonis) using unweighted UniFrac. It doesn't really matter,  but it would be good if the file names were consistent.

**Proposed Solution**

We pick one metric for permdisp and adonis, keep it consistent, and fix the file names.

**Comment by thermokarst** [comment]
I think @andrewsanchez fixed this a few weeks back in https://github.com/qiime2/docs/commit/42bac6e4af545a15f278bdc2b0dcc36ecc8e7d3d, can you confirm @jwdebelius?

**Comment by jwdebelius** [comment]
Less integrated; definitely a solution. Thanks, and sorry for not reading the code better!

**Comment by thermokarst** [comment]
Thanks for checking! I definitely didn't expect you to keep tabs on all the little code changes. This one came up during the FAES workshop in January, and @andrewsanchez was quick to patch it up.
