### ISSUE TITLE
Need URL to Latest Qiime2 Docs

### ISSUE THREAD

**Issue by dhakim87** [qiime2/docs#502]
**Improvement Description**
I'm adding a link out to the qiime2 documentation page from within the microsetta initiative site.  I want to direct users to the latest documentation, but the latest documentation changes all the time.  That is:

I currently send users out to https://docs.qiime2.org/2020.6/tutorials/moving-pictures/#taxonomic-analysis
I can replace with https://docs.qiime2.org/2021.2/tutorials/moving-pictures/#taxonomic-analysis, but that will be obsolete very soon.  

**Current Behavior**
Links to the documentation go stale monthly

**Proposed Behavior**
Can you expose a new url at: 
"https://docs.qiime2.org/latest/tutorials/moving-pictures/#taxonomic-analysis" and have it redirect the end user to the latest documentation?  It will still break if someone removes the moving-pictures tutorial, but at least it won't tell the end user the link is out of date forcing me to update on my end.

**Comment by colinvwood** [comment]
covered by #290
