### ISSUE TITLE
OTU clustering tutorial: closed-ref description is outdated

### ISSUE THREAD

**Issue by nbokulich** [qiime2/docs#509]
**Bug Description**
The OTU clustering tutorial text seems outdated, does not match the current outputs.

**Steps to reproduce the behavior**
[This section of the tutorial](https://github.com/qiime2/docs/blob/master/source/tutorials/otu-clustering.rst#closed-reference-clustering) describes two outputs (a table and a sequence file) and mentions that the sequence file consists of seqs that failed to match the reference. This does not match the current API.

**Expected behavior**
This should be updated to describe the current outputs; currently the rep seqs AND unmatched seqs are output as separate artifacts. This should be updated to better describe this.

**Comment by thermokarst** [comment]
This is even worse than a case where to docs were just "left behind" and needs to be updated - the tutorial was incorrect from the get-go.
