### ISSUE TITLE
can we import unaligned sequences in feature-classifier tutorial

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/docs#54]
In the feature-classifier.rst document we import aligned reads:

```shell
    qiime tools import \
      --type FeatureData[Sequence] \
      --input-path aligned_85_otu_sequences.fasta.gz \
      --output-path 85_otus.qza
```

and then run `extract-reads` where we extract based on the primers:

```shell
    qiime feature-classifier extract-reads \
      --i-sequences 85_otus.qza \
      --p-f-primer GTGCCAGCMGCCGCGGTAA \
      --p-r-primer GGACTACHVGGGTWTCTAAT \
      --p-read-length 100 \
      --o-reads ref-seqs.qza
```

@BenKaehler, can we import unaligned sequences here? It [looks like](https://github.com/qiime2/q2-feature-classifier/blob/6592ac69b7a14a8bbdee3b414ec9099d34788bf3/q2_feature_classifier/_gregex.py#L35) we just strip the gap characters, and unaligned reads are easier for users to provide in general (and also work directly if we want to train a classifier without extracting reads). So importing unaligned reads is preferable if it works.

**Comment by gregcaporaso** [comment]
ping @BenKaehler

**Comment by BenKaehler** [comment]
Hi @gregcaporaso, you can extract reads from unaligned sequences if you set

`--p-method match`

However, if the regex that we are using to find the primer binding sites fails for a given reference sequence, that reference sequence will be excluded from the output.

You may recall that by using the aligned sequences we are leveraging the alignment to locate the amplicon for sequences where the primers do not match exactly.

As an aside, @nbokulich mentioned that the amplicon locations and lengths can vary drastically for the ITS data sets. I was wondering whether we should implement a third method for amplicon extraction:

1. Find all the amplicons as we would in `match` mode.
2. Apply the `position` strategy to the sequences that were not matched in `match` mode.

What do you think? Thanks!

**Comment by gregcaporaso** [comment]
Thanks @BenKaehler, this makes sense. 

So I think we might want to split this in to two methods: one that requires aligned sequences (and therefore uses ``--p-method position``, and one that requires unaligned sequences (and therefore uses ``--p-method match``.

**Comment by gregcaporaso** [comment]
Discussed offline with @BenKaehler, and he was already thinking of going with this solution. I created an issue for this here: https://github.com/qiime2/q2-feature-classifier/issues/43.
