### ISSUE TITLE
migrate (or just remove) "Developing a QIIME 2 plugin" page

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/docs#554]
I forgot this existed:
https://docs.qiime2.org/2023.2/plugins/developing/#overview

We should move relevant content over to https://github.com/caporaso-lab/developing-with-qiime2

**Comment by Oddant1** [comment]
I believe it is already migrated https://github.com/caporaso-lab/developing-with-qiime2/blob/main/book/10-tutorial/10-plugins/00-intro.rst
