### ISSUE TITLE
BUG: broken link in importing data tutorial

### ISSUE THREAD

**Issue by colinvwood** [qiime2/docs#558]
In the `Casava 1.8 paired-end demultiplexed fastq` section of the importing tutorial, the link `Casava 1.8 demultiplexed` (first line of first paragraph) which points here `http://illumina.bioinfo.ucr.edu/ht/documentation/data-analysis-docs/CASAVA-FASTQ.pdf/view` is broken.

**Comment by kshitiz305** [comment]
Hi I wish to take this!!!

May I know which link should it point to.

**Comment by colinvwood** [comment]
Hi @kshitiz305, I don't believe we were able to find where this link was moved to if anywhere at all. It should probably be removed from the docs entirely unless you can find the original resource.

**Comment by colinvwood** [comment]
@hagenjp is going to take this one
