### ISSUE TITLE
Importing fasta+qual instead of fastq

### ISSUE THREAD

**Issue by git-ingham** [qiime2/docs#56]
I have fasta+qual files.  Qiime1 has convert_fastaqual_fastq.py.  What's the equivalent in qiime2?  Or, even better, how to create a qiime2 artifact directly from the fasta+qual+mapping files?  I looked here, which seems to be the appropriate location:
https://docs.qiime2.org/2.0.6/tutorials/import-sequence-data/

**Comment by thermokarst** [comment]
Hi @git-ingham, thanks for reaching out! Can you please repost this question on our [user support forum](https://forum.qiime2.org)? You can use your Github credentials to log in there, so no need to create an additional account. Thanks!
