### ISSUE TITLE
add link to installation docs suggesting to search the forum when troubleshooting

### ISSUE THREAD

**Issue by colinvwood** [qiime2/docs#560]
@lizgehret suggested adding a link to search results on the forum for e.g. "trouble installing qiime2" underneath the existing installation instructions for users encountering errors. 
Preferable to a longer, often changing, and possibly confusing set of troubleshooting instructions.

**Comment by gregcaporaso** [comment]
Closing in favor of https://github.com/qiime2/docs/issues/560
