### ISSUE TITLE
MAINT: `cluster-features-denovo` tutorial needs new `--p-strand` param added

### ISSUE THREAD

**Issue by lizgehret** [qiime2/docs#574]
The 2024.2 release included the following API change to `cluster-features-denovo`: https://github.com/qiime2/q2-vsearch/pull/90

The vsearch tutorial should be updated to include the newly added `--p-strand` parameter.

@colinvwood this would be a good one to have @hagenjp work on while I'm OOO.

**Comment by hagenjp** [comment]
Hi @lizgehret,  since this is an optional parameter that we are exposing and we do not have a use case in the tutorials for the  non-default "both" option, is there any reason why this parameter should be added in the vsearch tutorial?

**Comment by lizgehret** [comment]
Hey @hagenjp - in the tutorial, you can include the default `--p-strand` parameter in the `cluster-features-denovo` commands, then include a bit of text that describes the non-default use-case. This should be added because it keeps our tutorial up to date with the associated API change!
