### ISSUE TITLE
Describe column name case insensitivity in metadata tutorial

### ISSUE THREAD

**Issue by AmandaBirmingham** [qiime2/docs#577]
**Improvement Description**
Extend the metadata tutorial to explicitly note that non-id column names must differ by more than just case.  See reference 1 below.

**Current Behavior**
Currently, the `Metadata` class allows instantiation with inputs containing column names that differ only by case, but this leads to an error if using the `get_ids()` method.  

**Proposed Behavior**
Add a sentence to the `metadata.rst` tutorial.  My suggestion is to modify https://github.com/qiime2/docs/blob/8510b64569b534363c874a944168de607ce4cf91/source/tutorials/metadata.rst?plain=1#L110 

to 

```
 - Must be unique without regard to case (e.g., columns `foo` and `Foo` in the same file are not allowed)
 ```

**References**
1. https://forum.qiime2.org/t/are-non-sample-id-column-names-case-insensitive-in-metadata-files/29508

**Comment by hagenjp** [comment]
Hi @AmandaBirmingham, we are looking into a solution for this one and its not as simple as we thought because this is not an intentional behavior within qiime2. I think we will want to find a better solution than just changing documentation. Many thanks for bringing this one to our attention!
