### ISSUE TITLE
include example of BIOM v2.1 import

### ISSUE THREAD

**Issue by jairideout** [qiime2/docs#64]
The [importing data](https://docs.qiime2.org/2.0.6/tutorials/import/) tutorial shows how to import a .biom file in BIOM v1.0 format. It'd be helpful to include an example of importing a BIOM v2.1 file, which is the more common case (and QIIME doesn't autodetect v2.1). This question came up on the forum [here](https://forum.qiime2.org/t/import-biom-error/267).

**Comment by gregcaporaso** [comment]
This would be good to get in there for the next release, since it'd be relatively simple to add.
