### ISSUE TITLE
Client-side URL "upgrade"

### ISSUE THREAD

**Issue by thermokarst** [qiime2/docs#73]
I am wondering if we should do something like the [Django docs](https://docs.djangoproject.com/en/1.7/ref/contrib/admin/), where we provide a "version selector", and also some way to indicate that an old doc is "stale" or "outdate" (see the red bar at the top of the page).

<img width="1440" alt="screen shot 2017-01-30 at 8 46 16 am" src="https://cloud.githubusercontent.com/assets/274668/22429676/9e73d454-e6c8-11e6-99a9-a37e282a56da.png">
<img width="570" alt="screen shot 2017-01-30 at 8 46 28 am" src="https://cloud.githubusercontent.com/assets/274668/22429677/9e777046-e6c8-11e6-866c-dc0ca9241af8.png">

**Comment by ebolyen** [comment]
:+1:, if we had that sidebar it would also be good to generate [canonical meta tags](http://docs.readthedocs.io/en/latest/canonical.html) to keep our search engine indexed content up to date, although that would be a maintenance burden, as we would have to map everything from version to version. (I wonder if a lightweight redirect app would work here? only things following the `rel=canonical` would notice it)

**Comment by jairideout** [comment]
👍 , having the sidebar + header warning would be really nice for the upcoming release since we'll then have three versions of the docs (with most users being split between 2.0.6 and 2017.2). How much work do you guys think it'd take to add that in? Setting up version-mappings with canonical meta tags sounds awesome but non-trivial, we'd probably need to defer that part.

**Comment by thermokarst** [comment]
We could just go with naive URL upgrades, resulting in a 404 if the path has been removed/renamed/etc. I think that is how the Django docs do it (at least once upon a time).

I suspect it would be doable for the upcoming release. :crossed_fingers:

**Comment by jakereps** [comment]
Did #88 resolve this issue, or is it pivoted for semantic urls?

**Comment by jairideout** [comment]
I'm down with closing it! Thanks @jakereps and @ebolyen!
